FROM alpine:3.14 AS build

RUN apk add --update --no-cache gcc g++ make musl-dev unzip wget

WORKDIR /usr/src

ARG CC65_VERSION=2.19
ARG SUPERFAMICONV_VERSION=0.9.2

RUN wget https://github.com/cc65/cc65/archive/V${CC65_VERSION}.zip -O cc65-${CC65_VERSION}.zip \
  && unzip cc65-${CC65_VERSION}.zip \
  && cd cc65-${CC65_VERSION} \
  && PREFIX=/opt/cc65 make \
  && PREFIX=/opt/cc65 make install \
  && find /opt/cc65/bin -type f -exec strip {} \;

WORKDIR /usr/src

RUN wget https://github.com/Optiroc/SuperFamiconv/archive/refs/tags/v${SUPERFAMICONV_VERSION}.zip \
  && unzip v${SUPERFAMICONV_VERSION}.zip \
  && cd SuperFamiconv-${SUPERFAMICONV_VERSION} \
  && make \
  && cp /usr/src/SuperFamiconv-${SUPERFAMICONV_VERSION}/bin/superfamiconv /usr/bin/superfamiconv

FROM alpine:3.14

RUN apk add --update --no-cache make wine

COPY --from=build /opt/cc65 /opt/cc65
COPY --from=build /usr/bin/superfamiconv /usr/bin/superfamiconv
ADD tools/Pcx2Snes.exe /opt/tools/windows/pcx2snes.exe

ENV PATH /opt/cc65/bin:$PATH

WORKDIR /project
